/**
 * Drift tests for the docs site's "Edit page" link. Starlight links each page
 * to `editLink.baseUrl` + the page's path relative to `docs/`; a page built by
 * a generator opts out with `editUrl: false`, so readers are never sent to
 * edit a file that the next sync would overwrite.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

import { renderReferenceMarkdown } from '../schema/adapters/render-adapter-reference.js';

// Vitest runs from the repo root, so resolve paths from cwd.
const root = process.cwd();
const docsDir = resolve(root, 'docs/src/content/docs');

/** Every Markdown page under the docs content collection, recursively. */
function pages(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return pages(path);
    return /\.mdx?$/.test(entry.name) ? [path] : [];
  });
}

/** The YAML frontmatter block of a Markdown page (without the fences). */
const frontmatter = (md: string) =>
  md.replace(/\r\n/g, '\n').match(/^---\n([\s\S]*?)\n---\n/)?.[1] ?? '';

const optsOut = (md: string) => /^editUrl: false$/m.test(frontmatter(md));
const isGenerated = (md: string) => md.includes('<!-- Generated by ');

describe('docs site — Edit page link', () => {
  it('points every page at its source on the next branch', () => {
    const config = readFileSync(resolve(root, 'docs/astro.config.mjs'), 'utf8');
    expect(config).toMatch(
      /editLink: \{\s*baseUrl:\s*'https:\/\/github\.com\/ebi-webcomponents\/protvista\/edit\/next\/docs\/',?\s*\}/
    );
  });

  it('is turned off on every generated page, and only there', () => {
    const all = pages(docsDir);
    const generated = all.filter((p) => isGenerated(readFileSync(p, 'utf8')));
    expect(generated.map((p) => relative(docsDir, p)).sort()).toEqual([
      'adapter-reference.md',
      'type-and-shape-vocabulary.md',
    ]);
    for (const page of all) {
      const md = readFileSync(page, 'utf8');
      expect(optsOut(md), relative(docsDir, page)).toBe(isGenerated(md));
    }
  });

  it('is turned off by the adapter reference generator', () => {
    expect(optsOut(renderReferenceMarkdown())).toBe(true);
  });
});
