/**
 * Pure, deterministic renderer for the feature type and shape vocabulary
 * page (`docs/src/content/docs/type-and-shape-vocabulary.md`).
 *
 * Driven solely by its `NightingaleVocabulary` argument (no clock, no
 * environment), so the byte-identity spec can re-render the page and compare
 * it to the checked-in file. Regenerate with `pnpm vocabulary:sync`.
 */

import {
  FEATURE_SHAPES,
  isPaintableColor,
  type NightingaleVocabulary,
  type ShapeCategory,
} from './feature-vocabulary.js';

export const FEATURE_VOCABULARY_MD_PATH =
  'docs/src/content/docs/type-and-shape-vocabulary.md';

const NIGHTINGALE_CONFIG_URL =
  'https://github.com/ebi-webcomponents/nightingale/blob/main/packages/nightingale-track/src/config.ts';

/** Escape a value for use inside a Markdown table cell. */
function cell(value: string): string {
  return value.replace(/\|/g, '\\|');
}

function swatch(color: string): string {
  return (
    `<span style="display:inline-block;width:0.9em;height:0.9em;` +
    `vertical-align:middle;border:1px solid currentColor;background:${color}"></span>`
  );
}

const CATEGORY_TEXT: Record<ShapeCategory, string> = {
  range: 'Stretches to cover the feature',
  symbol:
    'Fixed-size glyph; across more than one residue a line joins its ends',
  unknown: 'Not drawn — shows a question mark',
};

function typeTable(vocab: NightingaleVocabulary): string {
  const header =
    '| Type | Label | Default shape | Default colour | Meaning |\n|---|---|---|---|---|';
  const rows = Object.entries(vocab.types).map(([code, t]) => {
    const colour = isPaintableColor(t.color)
      ? `${swatch(t.color)} \`${t.color}\``
      : `\`${t.color}\` — not a valid colour, see [below](#broken-defaults)`;
    return `| \`${code}\` | ${cell(t.label)} | \`${t.shape}\` | ${colour} | ${cell(
      t.tooltip || '—'
    )} |`;
  });
  return [header, ...rows].join('\n');
}

function shapeTable(vocab: NightingaleVocabulary): string {
  const header = '| Shape | Drawn as | Default for |\n|---|---|---|';
  const rows = FEATURE_SHAPES.map((shape) => {
    const users = Object.entries(vocab.types)
      .filter(([, t]) => t.shape === shape)
      .map(([code]) => `\`${code}\``);
    return `| \`${shape}\` | ${CATEGORY_TEXT[vocab.shapeCategories[shape]]} | ${
      users.join(', ') || '—'
    } |`;
  });
  return [header, ...rows].join('\n');
}

function brokenDefaults(vocab: NightingaleVocabulary): string[] {
  const broken = Object.entries(vocab.types).filter(
    ([, t]) => !isPaintableColor(t.color)
  );
  if (broken.length === 0) return [];
  const lines: string[] = ['## Broken defaults', ''];
  lines.push(
    'These defaults are not valid colours. The browser ignores an invalid colour, ' +
      'so a feature of this type is drawn in whichever colour was set before it. ' +
      'Set `rendering.color` on the track to get a stable colour until the default is fixed.'
  );
  lines.push('');
  for (const [code, t] of broken) {
    lines.push(`- \`${code}\`: \`${t.color}\`.`);
  }
  lines.push('');
  return lines;
}

export function renderFeatureVocabularyMarkdown(
  vocab: NightingaleVocabulary
): string {
  const typeCount = Object.keys(vocab.types).length;
  const undrawn = FEATURE_SHAPES.filter(
    (s) => vocab.shapeCategories[s] === 'unknown'
  );
  const { color: fallbackColor, shape: fallbackShape } = vocab.fallback;

  const lines: string[] = [];
  lines.push('---');
  lines.push('title: Feature type and shape vocabulary');
  lines.push('---');
  lines.push('');
  lines.push(
    '<!-- Generated by `pnpm vocabulary:sync` from @nightingale-elements/nightingale-track. Do not edit by hand. -->'
  );
  lines.push('');
  lines.push(
    'Every feature record has a `type` (see [Load your own data](/protvista/your-data)). ' +
      "The viewer uses it to pick the feature's default colour and shape from a table built " +
      `into Nightingale, the library that draws the tracks. This page lists that table as ` +
      `shipped in \`@nightingale-elements/nightingale-track\` ${vocab.version}, the version ` +
      'the viewer draws with. It is generated from that package and kept in sync by drift ' +
      'tests, so it cannot silently diverge.'
  );
  lines.push('');

  lines.push('## How a feature gets its colour and shape');
  lines.push('');
  lines.push('The first of these that applies wins:');
  lines.push('');
  lines.push(
    "1. The track's `rendering.color` and `rendering.shape`. These apply to **every** " +
      'feature in the track, whatever its type.'
  );
  lines.push(
    `2. The default for the feature's \`type\`, from [the table below](#recognised-types).`
  );
  lines.push(`3. \`${fallbackColor}\` and \`${fallbackShape}\`.`);
  lines.push('');
  lines.push(
    '`type` is matched without regard to case, against either the type code ' +
      '(`ACT_SITE`) or the longer UniProt name (`active site`).'
  );
  lines.push('');

  lines.push('## Types ProtVista does not recognise');
  lines.push('');
  lines.push(
    `A \`type\` outside the table is drawn as a ${fallbackColor} ${fallbackShape}. ` +
      'The viewer shows no error or warning; Nightingale only logs the type name to ' +
      'the browser console. Every unrecognised type looks the same, so a track that ' +
      'mixes two of them cannot tell them apart.'
  );
  lines.push('');
  lines.push('### Worked example: a custom type');
  lines.push('');
  lines.push(
    'A lab marks its own hotspots with a `type` UniProt does not use:'
  );
  lines.push('');
  lines.push('```csv');
  lines.push('type,start,end,description,score');
  lines.push('HOTSPOT,132,140,Lab-defined mutational hotspot,0.87');
  lines.push('HOTSPOT,601,612,Lab-defined mutational hotspot,0.64');
  lines.push('```');
  lines.push('');
  lines.push(
    `On its own, each row draws as a ${fallbackColor} ${fallbackShape}. Give the track a ` +
      '`rendering` block to choose the look instead:'
  );
  lines.push('');
  lines.push('```yaml');
  lines.push('accession: P05067');
  lines.push('rows:');
  lines.push('  - id: hotspots');
  lines.push('    label: Hotspots');
  lines.push('    kind: features');
  lines.push('    data: ./hotspots.csv');
  lines.push('    rendering:');
  lines.push("      color: '#e67e22'");
  lines.push('      shape: roundRectangle');
  lines.push('```');
  lines.push('');
  lines.push(
    'Because `rendering` applies to the whole track, it also overrides the defaults of ' +
      'any recognised types in the same file. Keep custom types in their own file and ' +
      'track so the recognised ones keep their colours.'
  );
  lines.push('');

  lines.push('## Recognised types');
  lines.push('');
  lines.push(
    `${typeCount} type codes, in the order Nightingale's ` +
      `[type table](${NIGHTINGALE_CONFIG_URL}) lists them.`
  );
  lines.push('');
  lines.push(typeTable(vocab));
  lines.push('');
  lines.push(...brokenDefaults(vocab));

  lines.push('## Shapes');
  lines.push('');
  lines.push(
    `\`rendering.shape\` takes one of these ${FEATURE_SHAPES.length} names. The spellings ` +
      `(\`discontinuos\`) are Nightingale's. ${undrawn.length} of them ` +
      `(${undrawn.map((s) => `\`${s}\``).join(', ')}) are declared but not drawn by the ` +
      'canvas track, and show a question mark instead. So does any other name: the config ' +
      'accepts any string for `shape`, and a misspelt one is not reported.'
  );
  lines.push('');
  lines.push(shapeTable(vocab));
  lines.push('');

  return lines.join('\n');
}
